logging:
  level:
    ROOT: INFO
    ru.rgordeev: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload

  jackson:
    serialization:
      indent-output: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      auto-commit: false

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port=8080

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}